feat: Custom type and ref arg handling in SchemaProcessor with tests
aws-amplify/amplify-data pull request #412
Opened 2024-12-11 22:34 UTC by vaisshnavi7

Problem: 
-Custom type and ref arguments in custom queries and mutations were not properly handled in the SchemaProcessor, leading to incorrect GraphQL schema generation.
-Several integration tests in custom-operations.ts were previously skipped due to schema validation issues related to custom type argument features.

Related PR
-This PR addresses the skipped tests and completes the implementation started in [PR #402](https://github.com/aws-amplify/amplify-api-next/pull/402).

Changes: 
- Updated SchemaProcessor.ts to generate GraphQL input types for custom types and ref arguments.
- Modified the processing of custom operations to use these generated input types.
- Implemented `generateInputTypes` function to create GraphQL input types for custom structures.
- Expanded and fixed integration tests in custom-operations.ts:
  - Re-enabled previously skipped tests
  - Added new test for schema.transform() to ensure correct schema generation
  - Added new tests for mocked runtime behavior of client operations with custom type and ref arguments
- Updated test snapshots to reflect new schema generation behavior
- Adjusted test cases in CustomOperations.test.ts, client-schema.ts, and ssr-req-client.ts

Validation:
- Expanded existing integration tests in custom-operations.ts to cover new functionality, including:
  - A new test for schema.transform() to verify correct schema generation
  - New tests for mocked client operations with custom type and ref arguments
- Re-enabled and fixed previously skipped tests in custom-operations.ts
- Verified that all tests now pass, including those for custom types and ref arguments
- Deployed the schema using a sample application to verify:
  - Schema generation matches expectations.
  - Deployment succeeds without errors.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-12-18 18:32 UTC, iartemiev requested changes
I'm seeing some unexpected changes in the code and tests/snapshots, as called out in the comments. 

Let's baseline on the requirements. When custom query/mutation `arguments` contain non-scalar values (e.g., custom types or a refs to custom types), we should:

1. Define a GraphQL Input type from the arguments in the SDL output from `schema.transform()`
2. Reference this input type in the query/mutation field argument
3. The GraphQL Type definition for the custom type should remain in the SDL output

For example, given:
```ts
Location: a.customType({
  lat: a.float(),
  long: a.float(),
}),

addLocationToPost: a
  .mutation()
  .arguments({ postId: a.string(), location: a.ref('Location') })
  .handler(a.handler.custom({ entry: './source.js' }))
  .returns(a.boolean())
```
The GraphQL output should be:
```gql
type Location 
{
  lat: Float
  long: Float
}

input AddLocationToPostLocationInput 
{
  lat: Float
  long: Float
}

type Mutation {
  addLocationToPost(postId: string, location: AddLocationToPostLocationInput): Boolean
}
```

However, when I pull down the PR and run `schema.transform()` on the same schema , I get the following output:
```gql
type Location 
{
  lat: Float
  long: Float
}

type Mutation {
  addLocationToPost(postId: String, location: ID): Boolean
}
```
* Input type is not getting generated
* `addLocationToPost` field arg `location` is referencing type `ID` instead of the Input type

After making the requested changes, I recommend linking `@aws-amplify/data-schema` into a sample app and actually attempting to deploy some schemas with custom operations containing non-scalar `arguments` to make sure everything works as expected.

2024-12-18 18:32 UTC, iartemiev commented on packages/data-schema/__tests__/__snapshots__/CustomOperations.test.ts.snap
> -}
We shouldn't be dropping this type definition. If we're just left with
```gql
type Mutation {
  likePost(postId: String!): LikePostReturnType 
}
```
The field return type `LikePostReturnType` is referencing an undefined type. This schema would error during deployment

2024-12-18 18:32 UTC, iartemiev commented on packages/data-schema/__tests__/__snapshots__/CustomOperations.test.ts.snap
> -}
Same as above ^. This type definition should not get dropped

2024-12-18 18:32 UTC, iartemiev commented on packages/data-schema/__tests__/__snapshots__/CustomOperations.test.ts.snap
> -}
Same here and below

2024-12-18 18:32 UTC, iartemiev commented on packages/data-schema/src/SchemaProcessor.ts
> +        gqlFields.push(`${fieldName}: ID${fieldAuth}`);
Why does an input become a field of type `ID`?

2024-12-18 18:32 UTC, iartemiev commented on packages/integration-tests/__tests__/defined-behavior/2-expected-use/custom-operations.ts
> +      'mutationWithRefArg(refArg: ID): String',
Similarly to previous comments, these should all be input types, something like:
```ts
'queryWithCustomTypeArg(customArg: QueryWithCustomTypeArgInput): String',
'queryWithRefArg(refArg: QueryWithRefArgInput): String',
'mutateWithCustomTypeArg(customArg: MutateWithCustomTypeArgInput): String',
'mutationWithRefArg(refArg: MutationWithRefArgInput): String'
```

And we should also test that these Input types themselves are being emitted in `schema.transform()`

2024-12-18 18:32 UTC, iartemiev commented on packages/integration-tests/__tests__/defined-behavior/2-expected-use/__snapshots__/custom-operations.ts.snap
> +    mutation($customArg: ID) {
Here and below, `ID` is not the correct GraphQL data type for these operations. We should be referencing the Input type that is generated from our Custom Type

2024-12-18 18:32 UTC, iartemiev commented on packages/data-schema/src/SchemaProcessor.ts
> +          gqlFields.push(`${fieldName}: ID${fieldAuth}`);
Same here

2024-12-18 22:02 UTC, stocaaro commented on packages/data-schema/__tests__/CustomOperations.test.ts
> -        )
Are both of these cases covered under test? It might make sense to duplicate this test here to ensure we cover both inline custom types and ref custom types.

2024-12-18 22:02 UTC, stocaaro commented on packages/data-schema/__tests__/__snapshots__/ClientSchema.test.ts.snap
> -  "schema": "type A @model @auth(rules: [{allow: public, provider: apiKey}])
I'm not sure I understand why this changed. What caused this diff?

2024-12-18 22:02 UTC, stocaaro commented on packages/data-schema/__tests__/__snapshots__/ClientSchema.test.ts.snap
> -  "schema": "type A @model @auth(rules: [{allow: public, provider: apiKey}])
This is probably related to Ivan's comments below.

2025-01-07 19:58 UTC, stocaaro reviewed
How is the unit test branch coverage of the code we're introducing in this change?

2025-01-07 19:58 UTC, stocaaro commented on packages/data-schema/src/SchemaProcessor.ts
> +  isInput: boolean = false,
What does `isInput` mean in this context? Can the name be clearer?

Even before this change, this function is taking enough defaulted params that it might be worth using a named args object instead of receiving this long list of different args with defaults that we can't use depending on which ordered arg we want to override.

2025-01-07 19:58 UTC, stocaaro commented on packages/data-schema/src/SchemaProcessor.ts
> +            )[0];
Broader than this section, but I've been stuck in this section of code trying to parse out whats happening here for a few minutes. This block in particular is especially difficult to grok.

The SchemaProcessor has been a growing pile of ver pragmatic solutions for a while, that causes it to be hard to work/reason across. I don't think we should refactor it with this change, but this change has me wanting to prioritize a refactor.

In the meantime are there opportunities to make a pass across these changes aiming at adding clarity in structure, ie making it easier to understand for a reviewer or the next dev who needs to make related changes?

2025-01-08 16:46 UTC, iartemiev requested changes

2025-01-08 16:46 UTC, iartemiev commented on packages/data-schema/__tests__/__snapshots__/CustomOperations.test.ts.snap
> +"type CreateCustomTypePostReturnType {
Here and below, I'm seeing that the auth graphql directives (`@aws_api_key`,  `@aws_cognito_user_pools`, etc.) are now getting dropped from the generated types. 

Does this PR actually need to change anything about how return types are handled relative to `main`? I could be wrong, but AFAIK, we already support custom types and refs to custom types as the return types for custom queries and mutations.

2025-01-09 17:20 UTC, iartemiev approved these changes
Thanks for making the requested changes.

Approving merge to the feat branch.

There are a few changes in `SchemaProcessor.ts` that I'd like to review more closely, but I will defer that until the feat -> main PR is ready.

2025-01-09 17:44 UTC, stocaaro approved these changes

2025-01-09 18:27 UTC, merged